### ISSUE TITLE
Failed to build AST

### ISSUE THREAD

**Issue by benjaminloerincz** [google/summit-ast#49]
## Expected Behavior

Unknown / shouldn't say "Found 0 Apex source files" nor "Failed to build AST for 0 files"

## Actual Behavior
```bash
❯ bazel run :SummitTool './AccountController.cls'
INFO: Analyzed target //:SummitTool (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //src/main/java/com/google/summit:SummitTool up-to-date:
  bazel-bin/src/main/java/com/google/summit/SummitTool.jar
  bazel-bin/src/main/java/com/google/summit/SummitTool.jdeps
INFO: Elapsed time: 0.085s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/src/main/java/com/google/summit/SummitTool ./AccountController.cls
Feb 24, 2024 5:54:03 PM com.google.summit.SummitTool main
INFO: Summit AST Tool
Feb 24, 2024 5:54:03 PM com.google.summit.SummitTool main
INFO: Usage: SummitTool <Apex files or search directories>
Feb 24, 2024 5:54:03 PM com.google.summit.SummitTool main
INFO: Searching for Apex source at: ./AccountController.cls
Feb 24, 2024 5:54:03 PM com.google.summit.SummitTool main
WARNING: Invalid path ./AccountController.cls
java.nio.file.NoSuchFileException: ./AccountController.cls
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
        at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
        at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
        at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
        at java.base/java.nio.file.Files.find(Files.java:3942)
        at com.google.summit.SummitTool.main(SummitTool.kt:52)

Feb 24, 2024 5:54:03 PM com.google.summit.SummitTool main
INFO: Found 0 Apex source files
Feb 24, 2024 5:54:03 PM com.google.summit.SummitTool main
INFO: Failed to build AST for 0 files
```

## Steps to Reproduce the Problem

1. `git clone https://github.com/google/summit-ast google/summit-ast`
2. `cd google/summit-ast`
3. `export JAVA_HOME="$(dirname $(dirname $(realpath $(which javac))))"`
4. Create file `AccountController.cls` in project using this content:
```apex
public class AccountController {
    public static Account getAccount() {
        return new Account();
    }
}
```
5. Run `bazel run :SummitTool './AccountController.cls'` or `bazel run :SummitTool 'AccountController.cls'`

## Specifications

- Version: Latest commit, see https://github.com/google/summit-ast/commit/1f7511176f8f86593fcef548061d2df4e74f1b8d 
- Platform: Mac OS

**Comment by adangel** [comment]
It should work, if you use an absolute path name for AccountController.cls, e.g.

```
bazel run :SummitTool "$(pwd)/AccountController.cls"
```

**Comment by benjaminloerincz** [comment]
Hm, I still get an error:
```bash
~/GitHub/google/summit-ast                                                                       
❯ bazel run :SummitTool "$(pwd)/AccountController.cls"
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:SummitTool (61 packages loaded, 859 targets configured).
INFO: Found 1 target...
Target //src/main/java/com/google/summit:SummitTool up-to-date:
  bazel-bin/src/main/java/com/google/summit/SummitTool.jar
  bazel-bin/src/main/java/com/google/summit/SummitTool.jdeps
INFO: Elapsed time: 3.876s, Critical Path: 0.50s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/src/main/java/com/google/summit/SummitTool /Users/lrz/GitHub/google/summit-ast/AccountController.cls
Feb 25, 2024 4:53:25 PM com.google.summit.SummitTool main
INFO: Summit AST Tool
Feb 25, 2024 4:53:25 PM com.google.summit.SummitTool main
INFO: Usage: SummitTool <Apex files or search directories>
Feb 25, 2024 4:53:25 PM com.google.summit.SummitTool main
INFO: Searching for Apex source at: /Users/lrz/GitHub/google/summit-ast/AccountController.cls
Feb 25, 2024 4:53:25 PM com.google.summit.translation.Translate translate
INFO: Translated /Users/lrz/GitHub/google/summit-ast/AccountController.cls successfully. Created 16 nodes.
Feb 25, 2024 4:53:25 PM com.google.summit.SummitTool main
INFO: Found 1 Apex source files
Feb 25, 2024 4:53:25 PM com.google.summit.SummitTool main
INFO: Failed to build AST for 0 files
```

**Comment by adangel** [comment]
> INFO: Failed to build AST for 0 files

Means, there were no errors, so all files could be parsed and the AST could be built.

> INFO: Translated /Users/lrz/GitHub/google/summit-ast/AccountController.cls successfully. Created 16 nodes.

Means, parsing and AST building ("translating") was successfully for AccountController.cls. The AST consists of 16 nodes.

From the README:
> The primary output is an in-memory AST data structure. The library is intended to be integrated into other development tools.

So, in order to make use of Summit AST, you actually need to write a tool that calls Summit AST and uses this in-memory AST to do something.
